apiVersion: v1
kind: Pod
metadata:
  name: taskmanager-pod-template
spec:
  containers:
    # Do not change the main container name
    - name: flink-main-container
      resources:
        requests:
          ephemeral-storage: 10Gi
        limits:
          ephemeral-storage: 10Gi
      volumeMounts:
        - mountPath: /opt/flink/volumes/hostpath
          name: flink-volume-hostpath
        - mountPath: /opt/flink/log
          name: flink-logs
  volumes:
    - name: flink-volume-hostpath
      hostPath:
        path: /data/ssj-george/flink-pv/flink-volume-hostpath
        type: Directory
    - name: flink-logs
      hostPath:
  path: /data/ssj-george/flink-pv/flink-logs
  type: Directory