apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv-0
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /ewi_delta_data/ssj-george/minio-pv
    server: svm107.storage.tudelft.net
---
